export const environment = {
  production: false,
  baseHref: '/',
  host: 'https://localhost:44398/api/',
  loginService: 'v1/User/login',
  pipingService: 'v1/User/GetTopMenu',
  leftMenuService: 'v1/User/GetLeftMenu',
  quickLinkService: 'v1/User/GetQuickLink',
  basicDataService: 'v1/PipeMaster/GetBasicData',
  updateBasicDataService: 'v1/PipeMaster/UpdateBasicData',
  designDataService: 'v1/PipeMaster/GetDesignData',
  updateDesignDataService: 'v1/PipeMaster/UpdateDesignData',
  getCurrentItem: 'v1/User/GetPipeMasterCurrentMenu',
  getNextItem: 'v1/User/GetPipeMasterNextMenu',
  getPreviousItem: 'v1/User/GetPipeMasterPreviousMenu',
  getPOF_ICDetailsService: 'v1/POFIC/GetPOF_IC_Details',
  updatePOF_ICDetailsService: 'v1/POFIC',
  internalCorrosionDataService: 'v1/POFIC',
  updateInternalCorrosionDataService: 'v1/POFIC',
  externalCorrosionDataService: 'v1/POFEC',
  updateExternalCorrosionDataService: 'v1/POFEC',
  getAllStructuralMinThkService: 'v1/StructuralMinThk/GetAll',
  getStructuralMinThkService: 'v1/StructuralMinThk/Get',
  updateStructuralMinThkService: 'v1/StructuralMinThk',
  createStructuralMinThkService: 'v1/StructuralMinThk',
  materialCodesDropdownListService: 'v1/MaterialCodes/DropdownList',
  insulationTypesListService: 'v1/InsulationType/DropdownList',
  materialStdListService: 'v1/MaterialMaster/MaterialStdDropdownList',
  materialGradeListService: 'v1/MaterialMaster/MaterialGradeDropdownList',
  pipeReportListService: 'v1/PipeReport/GetByEquipmentNo',
  addPipeReportService: 'v1/PipeMaster/GetByEquipmentNo',
  inspectionStrategyService: 'v1/InspectionStrategy/GetByEquipmentNo',
  observations: 'v1/PipeReport/GetAllObservations',
  addNewPipeReportService: 'v1/PipeReport',
  updatePipeReportService: 'v1/PipeReport',
  editPipeReportService: 'v1/PipeReport/GetByReportNo',
  corrosionStudyListService: 'v1/CorrosionStudy/GetBySearchFilters',
  addNewCorrosionStudyService: 'v1/CorrosionStudy',
  updateCorrosionStudyService: 'v1/CorrosionStudy',
  corrosionPipeCluster: 'v1/CorrosionStudy/GetPipeClustersByLoopNo',
  currentRiskMatrix:'v1/RiskAnalysis/GetCurrentRiskMatrix',
  currentRiskChart:'v1/RiskAnalysis/GetCurrentRiskChart',
  currentRiskSheet:'v1/RiskAnalysis/GetCurrentRiskSheet',
  analysisRiskMatrix:'v1/RiskAnalysis/GetAnalysisRiskMatrix',
  analysisRiskChart:'v1/RiskAnalysis/GetAnalysisRiskChart',
  analysisRiskSheet:'v1/RiskAnalysis/GetAnalysisRiskSheet',
  analyzeRisk:'v1/RiskAnalysis/AnalyzeRisk',
  corrosionByLoopNoService: 'v1/CorrosionStudy/GetByLoopNo',
  getCompanyService: 'v1/Company',
  importPipeMasterService: 'v1/PipeMaster/Import',
  uploadPipeMasterService: 'v1/PipeMaster/Upload',
};
